GET http://localhost:8080/ticks/sort=messageTimestamp?rics=MSFT&docTypes=TAS,TAQ&totalTicks=10000&pinStart=true&startTime=2024-10-07T00:00:00.0000000Z&endTime=2024-10-07T23:59:59.9999999Z&includeNullValues=true

### Example with specific fields (only return messageTimestamp, price, and volume)
GET http://localhost:8080/ticks/sort=messageTimestamp?rics=MSFT&docTypes=TAS,TAQ&totalTicks=10000&pinStart=true&startTime=2024-10-07T00:00:00.0000000Z&endTime=2024-10-07T23:59:59.9999999Z&includeNullValues=true&fields=messageTimestamp,price,volume