ric:
  cosmos:
    rics:
      ricGroup1:
        uri: ${ricGroup1.databaseAccount}
        databaseId: ric_database
      ricGroup2:
        uri: ${ricGroup2.databaseAccount}
        databaseId: ric_database
    shardCount: 8
  mappings:
    MSFT:
      ricName: MSFT
      ricGroupId: ricGroup1
    AAPL:
      ricName: AAPL
      ricGroupId: ricGroup2
    GOOGL:
      ricName: GOOGL
      ricGroupId: ricGroup2


