ric:
  cosmos:
    rics:
      ricGroup1:
        uri: https://abhm-cosmosdb-account-ephemeral.documents.azure.com:443/
        databaseId: ric_database
      ricGroup2:
        uri: https://abhm-cosmos-single-write.documents.azure.com:443/
        databaseId: ric_database
    shardCount: 8
  mappings:
    MSFT:
      ricName: MSFT
      ricGroupId: ricGroup1
    AAPL:
      ricName: AAPL
      ricGroupId: ricGroup2
    GOOGL:
      ricName: GOOGL
      ricGroupId: ricGroup2


